export const ADD_STAFF = 'ADD_STAFF';

export const STAFFS_LOADING = 'STAFFS_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';
export const ADD_STAFFS = 'ADD_STAFFS';

export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';
export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';

export const STAFFSSALARY_LOADING = 'STAFFSSALARY_LOADING';
export const STAFFSSALARY_FAILED = 'STAFFSSALARY_FAILED';
export const ADD_STAFFSSALARY= 'ADD_STAFFSSALARY';

export const DELETE_STAFF_SUCCESS = 'DELETE_STAFF_SUCCESS';
export const DELETE_STAFF_LOADING = 'DELETE_STAFF_LOADING';

export const UPDATE_STAFFS_SUCCESS = 'UPDATE_STAFFS_SUCCESS';